# Generated by Django 4.1.7 on 2023-05-17 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_category_id_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
        ),
    ]
