# Generated by Django 4.1.7 on 2023-05-28 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('customer_pms_post', 'customer_pms_post2'), ('customer_pms_post3', 'customer_pms_post4'))},
        ),
        migrations.RemoveField(
            model_name='post',
            name='category_id',
        ),
    ]
