# Generated by Django 4.1.7 on 2023-05-28 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_options_remove_post_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
        ),
    ]
