# Generated by Django 4.1.7 on 2023-03-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post2'),
    ]

    operations = [
        migrations.AddField(
            model_name='post2',
            name='categoryId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
