# Generated by Django 4.1.7 on 2023-03-06 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post2_categoryid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post2',
            old_name='categoryId',
            new_name='category_id',
        ),
    ]
