# Generated by Django 4.1.7 on 2023-04-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='choice',
            field=models.CharField(blank=True, choices=[('aku', 'aku'), ('kamu', 'kamu')], max_length=255, null=True),
        ),
    ]
